class Chat {
  final String name, lastMessage, image, time;
  final bool isActive;

  Chat({
    this.name = '',
    this.lastMessage = '',
    this.image = '',
    this.time = '',
    this.isActive = false,
  });
}

List chatsData = [
  Chat(
    name: "Ayah",
    lastMessage: "Iya",
    image: "asset/images/user_9.png",
    time: "3m ago",
    isActive: false,
  ),
  Chat(
    name: "Ibu",
    lastMessage: "siap",
    image: "asset/images/user_14.png",
    time: "8m ago",
    isActive: true,
  ),
  Chat(
    name: "Ipul",
    lastMessage: "Paan si lu",
    image: "asset/images/user_7.png",
    time: "5d ago",
    isActive: false,
  ),
  Chat(
    name: "ical",
    lastMessage: "Sama-sama :)",
    image: "asset/images/user_17.png",
    time: "5d ago",
    isActive: true,
  ),
  Chat(
    name: "Amanda",
    lastMessage: "Okay",
    image: "asset/images/user_5.png",
    time: "6d ago",
    isActive: false,
  ),
  Chat(
    name: "Panji",
    lastMessage: "Hope you are doing well...",
    image: "asset/images/user_8.png",
    time: "3m ago",
    isActive: false,
  ),
  Chat(
    name: "Abiyyu",
    lastMessage: "Hello Abdullah! I am...",
    image: "asset/images/user_11.png",
    time: "8m ago",
    isActive: true,
  ),
  Chat(
    name: "Yusuf",
    lastMessage: "Do you have update...",
    image: "asset/images/user_16.png",
    time: "5d ago",
    isActive: false,
  ),
  Chat(
    name: "Dhifa",
    lastMessage: "Hope you are doing well...",
    image: "asset/images/user_14.png",
    time: "3m ago",
    isActive: false,
  ),
  Chat(
    name: "Nopal",
    lastMessage: "Hello Abdullah! I am...",
    image: "asset/images/user_6.png",
    time: "8m ago",
    isActive: true,
  ),
  Chat(
    name: "wira",
    lastMessage: "Do you have update...",
    image: "asset/images/user_14.png",
    time: "5d ago",
    isActive: false,
  ),
  Chat(
    name: "Jacob Jones",
    lastMessage: "You’re welcome :)",
    image: "asset/images/user_4.png",
    time: "5d ago",
    isActive: true,
  ),
  Chat(
    name: "Danis",
    lastMessage: "Makasih",
    image: "asset/images/user_15.png",
    time: "6d ago",
    isActive: false,
  ),
  Chat(
    name: "Fathkim",
    lastMessage: "Serah dah",
    image: "asset/images/user_13.png",
    time: "3m ago",
    isActive: false,
  ),
  Chat(
    name: "Esther Howard",
    lastMessage: "Hello Abdullah! I am...",
    image: "asset/images/user_2.png",
    time: "8m ago",
    isActive: true,
  ),
  Chat(
    name: "Raka",
    lastMessage: "Ayo bang",
    image: "asset/images/user_12.png",
    time: "5d ago",
    isActive: false,
  ),
  Chat(
    name: "Nopal DQA",
    lastMessage: "Hope you are doing well...",
    image: "asset/images/user_10.png",
    time: "3m ago",
    isActive: false,
  ),
  Chat(
    name: "Nopal",
    lastMessage: "Hello Abdullah! I am...",
    image: "asset/images/user_6.png",
    time: "8m ago",
    isActive: true,
  ),
  Chat(
    name: "Ipul",
    lastMessage: "Do you have update...",
    image: "asset/images/user_7.png",
    time: "5d ago",
    isActive: false,
  ),
  Chat(
    name: "Jacob Jones",
    lastMessage: "You’re welcome :)",
    image: "asset/images/user_4.png",
    time: "5d ago",
    isActive: true,
  ),
  Chat(
    name: "Albert Flores",
    lastMessage: "Thanks",
    image: "asset/images/user_5.png",
    time: "6d ago",
    isActive: false,
  ),
  Chat(
    name: "Panji",
    lastMessage: "Kapan tan ?",
    image: "asset/images/user_8.png",
    time: "3m ago",
    isActive: false,
  ),
  Chat(
    name: "Esther Howard",
    lastMessage: "Hello Abdullah! I am...",
    image: "asset/images/user_2.png",
    time: "8m ago",
    isActive: true,
  ),
  Chat(
    name: "Ralph Edwards",
    lastMessage: "Do you have update...",
    image: "asset/images/user_3.png",
    time: "5d ago",
    isActive: false,
  ),
];
